# Generated by Django 5.0.8 on 2025-08-13 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم نوع اللعبة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود نوع اللعبة')),
                ('category', models.CharField(choices=[('electronic', 'ألعاب إلكترونية'), ('mechanical', 'ألعاب ميكانيكية'), ('inflatable', 'ألعاب هوائية'), ('vehicles', 'مركبات'), ('arcade', 'ألعاب أركيد'), ('vr', 'واقع افتراضي')], max_length=50, verbose_name='الفئة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع لعبة',
                'verbose_name_plural': 'أنواع الألعاب',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفندق')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
            ],
            options={
                'verbose_name': 'فندق',
                'verbose_name_plural': 'الفنادق',
            },
        ),
        migrations.CreateModel(
            name='GameZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنطقة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المنطقة')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='المساحة')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('opening_date', models.DateField(verbose_name='تاريخ الافتتاح')),
                ('revenue_account', models.CharField(blank=True, max_length=20, verbose_name='رقم حساب الإيرادات')),
                ('expense_account', models.CharField(blank=True, max_length=20, verbose_name='رقم حساب المصروفات')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'منطقة ألعاب',
                'verbose_name_plural': 'مناطق الألعاب',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المخزن')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المخزن')),
                ('location', models.CharField(max_length=300, verbose_name='الموقع')),
                ('warehouse_type', models.CharField(choices=[('main', 'مخزن رئيسي'), ('branch', 'مخزن فرعي'), ('maintenance', 'مخزن صيانة'), ('spare_parts', 'مخزن قطع غيار')], max_length=20, verbose_name='نوع المخزن')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
            },
        ),
    ]
