# Generated by Django 5.0.8 on 2025-08-13 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير عام'), ('zone_manager', 'مدير منطقة'), ('accountant', 'محاسب'), ('cashier', 'أمين صندوق'), ('viewer', 'مستعلم')], default='viewer', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('can_access_all_zones', models.BooleanField(default=False, verbose_name='الوصول لجميع المناطق')),
                ('preferred_currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة المفضلة')),
                ('dashboard_layout', models.CharField(default='default', max_length=20, verbose_name='تخطيط لوحة التحكم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('allowed_zones', models.ManyToManyField(blank=True, to='core.gamezone', verbose_name='المناطق المسموحة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
