# Generated by Django 5.0.8 on 2025-08-16 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, verbose_name='رقم الفاتورة')),
                ('bill_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الفاتورة')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي قبل الضرائب')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الضرائب')),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكاليف أخرى')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('posted', models.BooleanField(default=False, verbose_name='مرحلة')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gamezone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'فاتورة مشتريات',
                'verbose_name_plural': 'فواتير المشتريات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts', verbose_name='حساب التكلفة/المخزون')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasebill')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchasebill', verbose_name='فاتورة مرتبطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gamezone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'مرتجع مشتريات',
                'verbose_name_plural': 'مرتجعات المشتريات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasereturn')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المورد')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
            },
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier', verbose_name='المورد'),
        ),
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('transaction_type', models.CharField(choices=[('bill', 'فاتورة مشتريات'), ('return', 'مرتجع مشتريات'), ('payment', 'سداد لمورد'), ('adjustment', 'تسوية'), ('opening', 'رصيد افتتاحي')], max_length=20, verbose_name='النوع')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مدين (لصالح الشركة)')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='دائن (على الشركة)')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الجاري')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('reference_type', models.CharField(blank=True, max_length=20, verbose_name='نوع المرجع')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'كشف حساب مورد',
                'verbose_name_plural': 'كشوف حسابات الموردين',
                'ordering': ['-trans_date', '-id'],
            },
        ),
    ]
