# Generated by Django 5.0.8 on 2025-08-13 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('account_name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='رقم الآيبان')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='رمز السويفت')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('chart_account_code', models.CharField(blank=True, max_length=20, verbose_name='رقم الحساب في دليل الحسابات')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True, verbose_name='العملة')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد')),
                ('chart_account_code', models.CharField(blank=True, max_length=20, verbose_name='رقم الحساب في دليل الحسابات')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'خزينة',
                'verbose_name_plural': 'الخزائن',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='تاريخ المعاملة')),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('fee', 'رسوم'), ('interest', 'فوائد')], max_length=20, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='المستفيد')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='الغرض')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد بعد المعاملة')),
                ('journal_entry_id', models.IntegerField(blank=True, null=True, verbose_name='رقم قيد اليومية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.bankaccount', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'معاملة بنكية',
                'verbose_name_plural': 'المعاملات البنكية',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('treasury', 'خزينة'), ('bank', 'بنك')], max_length=10, verbose_name='نوع الحساب')),
                ('transaction_type', models.CharField(choices=[('revenue', 'إيراد'), ('expense', 'مصروف'), ('bank_deposit', 'إيداع بنكي'), ('bank_withdrawal', 'سحب من البنك'), ('exchange_in', 'تحويل داخل'), ('exchange_out', 'تحويل خارج'), ('partner_payment', 'دفعة شريك'), ('opening', 'رصيد أول المدة'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('reference_type', models.CharField(blank=True, max_length=20, verbose_name='نوع المرجع')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المعاملة')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treasury.bankaccount', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treasury.treasury', verbose_name='الخزينة')),
            ],
            options={
                'verbose_name': 'معاملة خزينة',
                'verbose_name_plural': 'معاملات الخزينة',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
