# Generated by Django 5.0.8 on 2025-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('revenue', 'إيراد'), ('expense', 'مصروف'), ('expense_reversal', 'عكس مصروف'), ('revenue_reversal', 'عكس إيراد'), ('bank_deposit', 'إيداع بنكي'), ('bank_withdrawal', 'سحب من البنك'), ('exchange_in', 'تحويل داخل'), ('exchange_out', 'تحويل خارج'), ('partner_payment', 'دفعة شريك'), ('opening', 'رصيد أول المدة'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع المعاملة'),
        ),
    ]
