# Generated by Django 5.0.8 on 2025-08-13 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='اسم الشريك')),
                ('partner_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة'), ('investor', 'مستثمر')], max_length=20, verbose_name='نوع الشريك')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='الرقم القومي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الشريك %')),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الاستثمار')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('partner_account', models.CharField(blank=True, max_length=20, verbose_name='رقم حساب الشريك')),
                ('share_expenses', models.BooleanField(default=True, verbose_name='يتحمل المصروفات')),
                ('expense_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة المصروفات %')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='core.gamezone', verbose_name='منطقة الألعاب')),
            ],
            options={
                'verbose_name': 'شراكة',
                'verbose_name_plural': 'الشراكات',
                'unique_together': {('zone', 'partner_name')},
            },
        ),
        migrations.CreateModel(
            name='PartnerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي'), ('check', 'شيك'), ('credit_card', 'بطاقة ائتمان')], max_length=20, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('treasury_updated', models.BooleanField(default=False, verbose_name='تم تحديث الخزينة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerships.partnership', verbose_name='الشراكة')),
            ],
            options={
                'verbose_name': 'دفعة شريك',
                'verbose_name_plural': 'دفعات الشركاء',
            },
        ),
        migrations.CreateModel(
            name='PartnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='تاريخ المعاملة')),
                ('transaction_type', models.CharField(choices=[('revenue_share', 'حصة من الإيرادات'), ('expense_share', 'حصة من المصروفات'), ('payment_received', 'مبلغ مستلم'), ('payment_made', 'مبلغ مدفوع'), ('adjustment', 'تسوية'), ('opening_balance', 'رصيد أول المدة')], max_length=20, verbose_name='نوع المعاملة')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مدين (له)')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دائن (عليه)')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد الجاري')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('revenue_id', models.IntegerField(blank=True, null=True, verbose_name='رقم الإيراد')),
                ('expense_id', models.IntegerField(blank=True, null=True, verbose_name='رقم المصروف')),
                ('payment_id', models.IntegerField(blank=True, null=True, verbose_name='رقم الدفعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerships.partnership', verbose_name='الشراكة')),
            ],
            options={
                'verbose_name': 'كشف حساب شريك',
                'verbose_name_plural': 'كشوف حسابات الشركاء',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
