# Generated by Django 5.0.8 on 2025-08-13 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20, unique=True, verbose_name='رقم الحساب')),
                ('account_name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات'), ('cost', 'تكلفة')], max_length=20, verbose_name='نوع الحساب')),
                ('level', models.IntegerField(default=1, verbose_name='المستوى')),
                ('is_main_account', models.BooleanField(default=False, verbose_name='حساب رئيسي')),
                ('balance_type', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10, verbose_name='طبيعة الرصيد')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccounts', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=20, unique=True, verbose_name='رقم القيد')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('entry_type', models.CharField(choices=[('revenue', 'إيراد'), ('expense', 'مصروف'), ('transfer', 'تحويل'), ('adjustment', 'تسوية'), ('opening', 'رصيد أول المدة'), ('closing', 'قفل حسابات')], max_length=20, verbose_name='نوع القيد')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الدائن')),
                ('reference_type', models.CharField(blank=True, max_length=20, verbose_name='نوع المرجع')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('posted', models.BooleanField(default=False, verbose_name='تم الترحيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gamezone', verbose_name='منطقة الألعاب')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('category', models.CharField(choices=[('rent', 'إيجارات'), ('maintenance', 'صيانة'), ('salary', 'رواتب'), ('transport', 'مواصلات'), ('utilities', 'مرافق'), ('marketing', 'دعاية وإعلان'), ('supplies', 'مستلزمات'), ('insurance', 'تأمين'), ('other', 'أخرى')], max_length=20, verbose_name='الفئة')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('charge_partners', models.BooleanField(default=True, verbose_name='تحميل على الشركاء')),
                ('partner_shares_calculated', models.BooleanField(default=False, verbose_name='تم حساب حصص الشركاء')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الإيصال')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='المورد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gamezone', verbose_name='منطقة الألعاب')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دائن')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='سعر الصرف')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccounts', verbose_name='الحساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'verbose_name': 'تفصيل قيد يومية',
                'verbose_name_plural': 'تفاصيل قيود اليومية',
            },
        ),
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('card', 'بطاقة'), ('mixed', 'مختلط')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('partner_shares_calculated', models.BooleanField(default=False, verbose_name='تم حساب حصص الشركاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gamezone', verbose_name='منطقة الألعاب')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'verbose_name': 'إيراد يومي',
                'verbose_name_plural': 'الإيرادات اليومية',
                'ordering': ['-date'],
                'unique_together': {('zone', 'date', 'currency')},
            },
        ),
    ]
